language: python

services:
- postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

cache: pip

python:
- '3.6'
- '3.7'
install:
- pip install tox-travis
- pip install python-coveralls
- pip install "virtualenv" "tox>=1.9"
- pip install -U importlib_metadata
script:
- COMMAND_PREFIX='coverage run --source=testapp,rest_models' QUIET=true tox

stages:
- test
- test_postgres
- deploy

jobs:
  include:
  # deploy if master and tag
  - stage: test_postgres
    python: '3.7'
    script: COMMAND_PREFIX='coverage run --source=testapp,rest_models' QUIET=true tox -e postgresql
  - stage: deploy
    python: '3.7'
    script: skip # to not run Travis' default script
    install: skip
    on:
      repo: Yupeek/django-rest-models
      tags: true
    deploy:
      provider: pypi
      user: yupeek

      password:
        secure: e24svC/SHS9PcbgTqv40QXsiziygb9KgYqz6pjwI5eIM05s5a9kuF7OadV+Kd2Gq/XlxpPn9wKomYUoBLwg1eZs4kpAo8qDMZp51xi9hR8gYHmmOzvmV2NTfSdeEKEGHNbSNid3GUOZiKm3IDw3ym7983kkLLVsdRlty8b/X8kqPH+m+M+1lXl7d5l4rH3+rov8udasBGX4h3x8qdI1YKZfiL33gW632Fr5rrkC3ISTX5ClI8SgDZHdc3uG8C6u9TLTwjcxrAtTvIBHIg8BX4i8HR0o8LdyfHARqZbk6g2N6sK5B1kIgXumiY2gA9g5cnz/TEC+ZJkn2AueEHJkpY5gyJnmiC67ro3v0h3Gkl3v4H7k3GhbmZiMjA3Vzt6Ea/hBCNk7YfBo22j8h65F8KuS24OiQjxPO+UFI6bzYnAvP6HQdiM9M3Wai7Szv+GYRLRqZt5psxEtg9pvqZLLmr6LW+kvFjYG1bYVGNZG2Lr0VLQ99PVfV+LwV74XpWAUBLFsGuTAEdIuWUln0zeXwLRh/FQXhthVc1/A9uEviBVT9yaiYG8KvRd43b5NGlaXsPjH4bkj3xVpEBE5OhO64C33sNBABI0xbaFzLQgbrH4FP1MPhzxxK4p5GiXa1w+WfPtF/gFYfBGjP7NtDkKhFAS/UZ/WoPgRWQXkBtqWBnw8=

      distributions: sdist bdist_wheel
      skip_existing: true
